project:
  type: book
  output-dir: docs

book:
  title: "Policía para el Desarrollo Humano (PDH)"
  author: "Andrés Pérez Coronado"
  date: "9/3/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - cap1.qmd
    - cap2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

