project:
  type: book
  output-dir: docs

book:
  title: "Guía de implementación de Policía para el Desarrollo Humano (PDH)"
  author: "Equipo SUDIR"
  date: "9/3/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - cap1.qmd
    - cap2.qmd
    - cap3.qmd
    - cap4.qmd
    - cap5.qmd
    - summary.qmd
    - references.qmd
    - apend1.qmd
    - apend2.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

