# Identificar las causas, factores y redes de la violencia y el delito

## Microterritorios multicrimen

```{r}
library(sf)
library(ks)
library(mapview)
library(dplyr)
library(readr)

municipios <- st_read("mun_13_02_2018/Municipios.shp")
municipios <- st_as_sf(municipios, crs = 4326)
unidad <- municipios[municipios$NOM_DEPART == 'TOLIMA',]
unidad <- unidad[unidad$NOM_MUNICI %in% c('IBAGUÉ', 'CAJAMARCA',
                                       'PIEDRAS', 'ALVARADO'),]
unidad <- st_transform(unidad, 4326) 

grid <- st_make_grid(unidad, cellsize = 0.01/5)
grid_kde <- do.call(rbind, st_centroid(grid)) %>% 
  as_tibble()

delitos <- read_csv("~/Downloads/delitos.csv", 
                    locale = locale(decimal_mark = ","))

delitos <- delitos[delitos$LONGITUD < -60 & delitos$LATITUD > 4,]

unique(delitos$DESCRIPCION_CONDUCTA)
View(table(delitos$DESCRIPCION_CONDUCTA))

vida_homicidio <- c("ARTÍCULO 103. HOMICIDIO", "ARTÍCULO 104A. FEMINICIDIO")

vida_lesiones <- c("ARTÍCULO 111. LESIONES PERSONALES", "ARTICULO 120 LESIONES CULPOSAS", "ARTÍCULO 119. LESIONES PERSONALES ( CIRCUNSTANCIAS DE AGRAVACIÓN)",
                   "ARTÍCULO 113. DEFORMIDAD", "ARTÍCULO 116. PÉRDIDA ANATÓMICA O FUNCIONAL DE UN ÓRGANO O MIEMBRO", "ARTÍCULO 229. VIOLENCIA INTRAFAMILIAR")

vida_sexual <- c("ARTÍCULO 206. ACTO SEXUAL VIOLENTO", "ARTÍCULO 205. ACCESO CARNAL VIOLENTO", "ARTÍCULO 210. ACCESO CARNAL O ACTO SEXUAL ABUSIVO CON INCAPAZ DE RESISTIR",
                 "ARTÍCULO 210 A. ACOSO SEXUAL", "ARTÍCULO 207. ACCESO CARNAL O ACTO SEXUAL EN PERSONA PUESTA EN INCAPACIDAD DE RESISTIR", "ARTÍCULO 213. INDUCCIÓN A LA PROSTITUCIÓN",
                 "ARTÍCULO 214. CONSTREÑIMIENTO A LA PROSTITUCIÓN")

vida_sexual_nna <- c("ARTÍCULO 208. ACCESO CARNAL ABUSIVO CON MENOR DE 14 AÑOS", "ARTÍCULO 209. ACTOS SEXUALES CON MENOR DE 14 AÑOS",
              "ARTÍCULO 218. PORNOGRAFÍA CON MENORES", "ARTÍCULO 219 A. UTILIZACIÓN O FACILITACIÓN DE MEDIOS DE COMUNICACIÓN PARA OFRECER SERVICIOS SEXUALES DE MENORES",
              "ARTÍCULO 217 A. DEMANDA DE EXPLOTACION SEXUAL COMERCIAL DE PERSONA MENOR DE 18 AÑOS DE EDAD", "ARTÍCULO 213 A. PROXENETISMO CON MENOR DE EDAD",
              "ARTÍCULO 126. LESIONE CULPOSAS AL FETO", "ARTÍCULO 217. ESTÍMULO A LA PROSTITUCIÓN DE MENORES")

ingreso_extorsion <- c("ARTÍCULO 244. EXTORSIÓN")

ingreso_hurto <- c("ARTÍCULO 239. HURTO PERSONAS", "ARTÍCULO 239. HURTO ENTIDADES COMERCIALES", "ARTÍCULO 239. HURTO RESIDENCIAS",
             "ARTÍCULO 239. HURTO AUTOMOTORES", "ARTÍCULO 239. HURTO PIRATERÍA TERRESTRE", "ARTÍCULO 239. HURTO ENTIDADES FINANCIERAS", 
             "ARTÍCULO 243. ABIGEATO")

dimension <- ingreso_hurto
  
multicrimen_ubano <- subset(delitos, 
                      delitos$DESCRIPCION_CONDUCTA %in% dimension &
                        delitos$ZONA == 'URBANA')
multicrimen_rural <- subset(delitos, 
                      delitos$DESCRIPCION_CONDUCTA %in% dimension &
                        delitos$ZONA == 'RURAL')

coord_urbana <- multicrimen_ubano[,c('LONGITUD','LATITUD')]
coord_rural  <- multicrimen_rural[,c('LONGITUD','LATITUD')]

kd_urbana <- kde(coord_urbana, Hpi(coord_urbana, pilot="dscalar"), eval.points = grid_kde)
kd_rural <- kde(coord_rural, Hpi(coord_rural, pilot="dscalar"), eval.points = grid_kde)

kde_urbana <- data.frame(x = kd_urbana[["eval.points"]][[1]], 
                  y = kd_urbana[["eval.points"]][[2]],
                  densidad = kd_urbana[["estimate"]])

kde_rural <- data.frame(x = kd_rural[["eval.points"]][[1]], 
                  y = kd_rural[["eval.points"]][[2]],
                  densidad = kd_rural[["estimate"]])

percentil_urbana <- quantile(kde_urbana$densidad, probs = 0.999)[[1]]
percentil_rural <- quantile(kde_rural$densidad, probs = 0.999)[[1]]

microterritorio_urbano <- kde_urbana[kde_urbana$densidad > percentil_urbana,]
microterritorio_rural <- kde_rural[kde_rural$densidad > percentil_rural,]

microterritorio_urbano <- st_as_sf(microterritorio_urbano,
                                  coords = c('x','y'), 
                                  crs = 4326)
microterritorio_rural <- st_as_sf(microterritorio_rural,
                             coords = c('x','y'), 
                             crs = 4326)

mapview(list(microterritorio_urbano, microterritorio_rural),
        legend = F, color = 'blue') 
```

## Causas estructurales de la violencia y el delito

Como lo define el Semillero de Gestión Pública de la Universidad del Rosario, son situaciones históricas que han trascendido en el tiempo y se encuentran inmersas implícitamente en la sociedad y generan en cierto modo algún tipo de violencia o delito. Estas pueden aparecer desde estructuras sociales, económicas, políticas, legales, religiosas y culturales, que pueden llegar a limitar el desarrollo de las capacidades de los individuos en la sociedad, convirtiéndose en un tipo de violencia.

A continuación, se explican cuáles son las causas más relevantes de la violencia y el delito en América Latina y el Caribe (ALC), que obran en diversos ámbitos de la vida social y de interacción comunitaria, porque al desaparecer la causa que induce a los hombres a abusar de sus libertades, desaparecerá el motivo que provoca tantas y tan antipáticas intervenciones de la policía (LLERAS, 2009), lo que significa un enfoque hacia la prevención que hacia el control.

Las causas son extraídas de diferentes informes de desarrollo humano de ALC para que estas permitan orientar las estrategias hacia el contexto local, el Informe de Desarrollo Humano de Centro América es una fuente importante de consulta.

### Inseguridades invisibles

Son las causas presentes en la sociedad y que de ellas se habla, pero son difíciles de visibilizar, principalmente porque ocurren inconscientemente, se vuelven un hábito o se realizan al interior de los hogares. Además, su representación en los indicadores de seguridad ciudadana son difíciles de establecer y medir, puesto que la información depende mucho de la cultura y el nivel de denuncia frente a estos temas.

#### Discriminación

no consiste en estar expuesto a más riesgo, sino a un desbalance mayor o más marcado entre las amenazas y la protección del sistema social que ofrece a estas personas. Se encuentran las minorías étnicas, lingüísticas, nacionales, religiosas, orientación sexual y hasta políticas, que pueden ser víctimas de discriminación más o menos sistemática (PNUD, 2009), sin limitar este concepto se busca que abarque toda situación donde las personas se sientan segregadas.

#### Jóvenes y niños excluidos

El Informe de Desarrollo Humano de Centro América indica que los jóvenes requieren un especial análisis, pero se puede decir que causas estructurales combinadas de jóvenes excluidos, con dificultades para incorporarse a la vida laboral, baja educación y familias desarticuladas crean un universo vulnerable que constituye un mercado cautivo, para las bandas criminales o pandillas, que pueden ser vistas como una opción de vida para muchos niños y jóvenes, siendo estos grupos perpetradores de delitos, desde narcomenudeo hasta el secuestro (KliKsberG, 2010), hecho que limita el desarrollo humano desde edades tempranas.

Una niñez desprotegida, niños y niñas quienes son "invisibilizados" como ocurre también con los jóvenes, que tampoco se exceptúan del clima de violencia de la región. Son víctimas de homicidios de menores, menores delincuentes, abuso de las autoridades, maltrato en el hogar, abusos sexuales, explotación laboral y explotación sexual comercial (PNUD, 2009). Esta dualidad de ser víctimas y victimarios requiere una especial atención en el diseño de políticas públicas y de las intervenciones de la PDH.

#### Violencia contra las mujeres

Es otra causa de la inseguridad, que tiene en cuenta a la mujer como infractora, puesto que está presente frecuentemente en delitos más leves que los hombres, y como víctimas, pues perciben los riesgos y amenazas de forma diferente a los hombres, como en el caso de la violencia doméstica y sexual que las afecta más. De igual manera, son víctimas de la violencia contra la pareja, violencia sexual contra niñas y adolescentes y, sobre todo, la violencia intrafamiliar.

### Corrupción

Ocupa un lugar importante en las causas del delito producidas por la apropiación indebida de los bienes públicos (PNUD, 2013), es decir, del patrimonio colectivo. La corrupción es un motivo de indignación y escepticismo político, que, sin embargo, no tiende a percibirse como una forma de inseguridad, o como parte integral y apremiante del problema del crimen, al igual que nadie se siente víctima.

También produce daños y disminuye el ritmo de crecimiento económico que afecta la distribución equitativa de bienes y servicios, y lesiona la confianza en las instituciones (PNUD, 2009). Igualmente, la corrupción es causa de muchos delitos, y, un es delito en sí mismo, tiene causas que la propician, siendo principalmente: el irrespeto por lo público y "cultura del vivo", una institucionalización débil, fallas de regulación, fallas en la rendición de cuentas, los incentivos perversos por sanciones leves y beneficios grandes, y la insuficiencia del salario e inestabilidad laboral.

#### Poderes fácticos

Son grupos de presión cuyas acciones habituales están dentro de la ley, y, que, a menudo, reciben apoyo popular, defienden sus intereses pero comenten corrupción cuando usan su capacidad de influir y beneficiarse de las decisiones de los servidores públicos (PNUD, 2009), esto se refiere, también, de privados con intereses netamente económicos y políticos que no buscan el bien común.

#### Grandes desfalcos

Se tratan de personas, empresas o grupos poderosos que logran beneficios significativos gracias a la actuación ilegal de uno o varios funcionarios. El impacto en la legitimidad de la institucionalidad es severo (PNUD, 2009), un ejemplo, claro, es la asignación amañada de contratos. Infortunadamente, este tipo de corrupción afecta un gran número de personas e involucra igualmente fuertes sumas de dinero.

#### Corrupción gris

Opera en las esferas administrativas en la cotidianidad de los trámites y prestación de servicios públicos. Se representa en la venta de decisión o de servicio público rutinario, y el clientelismo que reparte servicios o puestos públicos a cambio de lealtad política o electoral (PNUD, 2009). Se podría decir que ya existe una práctica cultural de aceptación hacia este tipo de corrupción que desconoce el daño al estado de derecho, como es el caso de cambiar los votos por dinero.

#### Penetración del crimen organizado

Los delincuentes necesitan neutralizar o cooptar a las autoridades, para llevar a cabo muchas de sus actividades (PNUD, 2009). Se utiliza el poder económico criminal, para que los servidores públicos, de manera directa o indirecta, participen en sus actividades.

### Impacto de la globalización

La globalización, la apertura de fronteras, la generalización de modelos de desarrollo, -fundados sobre el comercio exterior-, son tendencias irreversibles (COUFFIGNAL, 2013). La criminalidad y la violencia han aprovechado la globalización, para extender redes criminales, como en el caso del tráfico de drogas. Esto genera nuevos retos, para la seguridad ciudadana y aumenta las oportunidades para el delito y la fortaleza de las organizaciones criminales, como en inducir o agravar ciertos desajustes que erosionan el tejido social.

#### Globalización económica

Ofrece más oportunidades para la realización de delitos, en el entendido, que las tecnologías de la información y comunicación facilitan el crimen organizado para operar redes como de trata de personas o narcotráfico.

Acompañado por la desregularización de trámites bancarios o la abundancia de remesas hacia algunos países. Además de la nueva división internacional del trabajo, que esas tecnologías conllevan, (PNUD, 2009), la conveniencia económica de las multinacionales es más dinámica que la normatividad mundial para la reglamentación de la migración de fuerza laboral en el mundo.

Existen desajustes resultantes de la globalización económica relacionados con la inestabilidad propia de una economía que no depende de la expansión sostenida del mercado interno, sino, ante todo, de los altibajos internacionales y la precariedad del ingreso y de las relaciones de trabajo propias de los "sectores exportadores líderes" (remesas y maquila) (PNUD, 2009), además del impacto directo que esto genera, también establece una interdependencia global de las economías de todos los países del mundo con esta misma dinámica.

#### Globalización política

Tiene tres expresiones principales

-   el debilitamiento del Estado nacional que tiene un estado más reducido y busca ser atractivo económicamente, pero debilita sus capacidades como en el caso de la seguridad ciudadana;

-   la desregularización económica general que abrió puertas a la corrupción en el manejo de las privatizaciones; la desregularización de los mercados de trabajo que desmejoró las condiciones y estabilidad laboral; y

-   la emergencia de la "amenaza terrorista" como eje de una nueva geopolítica mundial, puesto que los gobiernos de forma consciente o inconsciente han tenido que enfrentar amenazas globales (PNUD, 2009), tal vez deja de lado el escenario interno, para atender prioridades extranjeras.

#### Globalización cultural

Tiene efecto por el bombardeo de noticias, entretenimiento y opiniones de los países del norte lo cual está generando la pérdida de identidad, consistente en el desarraigo, en verse forzado a dejar la propia historia, costumbres y hasta la propia lengua; y la perdida de rumbo que es consecuencia del ingreso a un universo posmoderno desde un universo premoderno que implica confusión de valores en lugar de pluralismo, oportunismo en lugar de escogencia y dispersión en lugar de diversidad (PNUD, 2009). Se podría inferir que las culturas fuertes, o de mayor tendencia, poco a poco van dominando a aquellas que tienen un referente local, folclórico o cultural.

### Desajustes internos

El informe de desarrollo humano para América Central (PNUD, 2009) explica, desde la teoría criminológica, que estos desajustes internos tienen efectos en tres vías así: 1) aumentan el número de individuos predispuestos a incurrir en acciones delictivas "semillero", 2) facilitan la comisión del delito "ocasiones" y 3) crean un marco o clima que tiende a creer que la violencia y la apropiación de lo ajeno son conductas aceptables "contexto".

#### Semillero

Se da porque las familias están en tensión y es el principal elemento para prevenir la delincuencia, las familias pueden educar en valores éticos o en el abuso del otro. Pero las familias están afectadas por hogares incompletos o monoparentales, habitualmente la jefatura del hogar es femenina, que en sí no son un problema, pero si es acompañada de abandono emocional y económico del padre, sumado a esto, una madre adolescente aumenta el riesgo de actitudes violentas o delincuenciales de los hijos.

Así el trauma del emigrante que crea un sentimiento de desasosiego y una incertidumbre acerca de su suerte, a veces, sin contar con la presencia de la familia en momentos decisivos, para formar la personalidad de un hijo o hija y sentir que la separación es inevitable (PNUD, 2009). Como se trató anteriormente en inseguridades invisibles, existe, también en el semillero, la abundancia de hombres y mujeres marginalizados y jóvenes sin futuro.

#### Ocasión

Es originada por una urbanización rápida y desordenada de las ciudades que son segregadas, puesto que ricos y pobres viven separados, sin planeación urbanística, ni espacios públicos suficientes para disfrutar los beneficios de la ciudad. Igualmente, impacta la criminalidad, en el hecho de que la baja calidad de viviendas y el hacinamiento parecen propiciar la violencia en las calles, con una urbanización desordenada que no puede proteger y reservar áreas de uso público, como lugares por excelencia para el encuentro y convivencia ciudadana, entre muchos otros.

La abundancia de armas permite la ocasión para el delito, existen armas de conflictos anteriores y armas modernas que vienen de otros países, principalmente del debido al intercambio por el tráfico de drogas, esas armas son el instrumento preferido de los delincuentes.

Los ciudadanos del común se arman para defenderse, y así se originan un círculo vicioso, puesto que la mera posesión de un arma es motivo para utilizarla (PNUD, 2009), entonces, en la mayoría de las ocasiones el arma se convierte en una respuesta instrumental al temor social por la inseguridad ciudadana.

Las drogas y el licor aportan a la ocasión del delito. No todos los consumidores de drogas o alcohol son criminales o violentos, pero existe una clara asociación entre episodios violentos y la ingesta de drogas o licor por parte de los victimarios o las víctimas (PNUD, 2009). Esta relación es de las pocas tan contundentes y trasversales a todas las culturas del mundo.

#### Contexto

Es la última vía de índice de pobreza, desajuste interno. El contexto está enmarcado por la economía de desigualdad y la exclusión (PNUD, 2009). Actualmente, uno de los principales problemas de la creencia de la inseguridad, es que la pobreza está directamente relacionada con la violencia y el delito, cuando se puede analizar que la pobreza no es el problema, sino la desigualdad social, porque uno de los errores más destacados en el diseño de estrategias para encarar estos temas, es plantear que en ALC hay pobreza y desigualdad, cuando en realidad hay pobreza porque hay altos niveles de desigualdad (KLISBERG, 2010). Aunque, pareciera que es un juego semántico de términos, el abordaje del constructo es radicalmente distinto y se refiere , este último, a las causas estructurales.

La política: guerras y transiciones, aunque las dictaduras y las guerras se acabaron, dejaron legados funestos para los países donde se desarrollaron. Uno agrava la amenaza de la inseguridad y otro dificulta la respuesta adecuada por parte del Estado. Existen rescoldos de la violencia política; varias generaciones crecieron en medio de la represión o de la guerra civil, así aprendieron que la violencia es un modo de sobrevivir y de vivir. Y esto, también, ha afectado las transiciones hacia la democracia que le abren espacio al enfoque del manejo militar de un problema civil (PNUD, 2009). Este aspecto es uno de los más complejos, pues se legitima la violencia, al punto de que se asume, como un elemento de identidad cultural.

La cultura de la violencia y trampa, expresan que no se nace violento o predador sino que se aprende a serlo. La violencia y la apropiación de hacerlo son maneras de lograr lo que uno busca; y cuando esas maneras se vuelven habituales, estamos ante una cultura de la violencia o de trampa (PNUD, 2009). En una sociedad desequilibrada, este tipo de culturas, es más efectiva en la consecución de recursos, que ceñirse al marco normativo y a la ética social.

### Factores socio económicos

El Informe de Desarrollo Humano para América Latina, 2013- 2014, indica que ni el crecimiento económico ni la reducción de la pobreza y el desempleo permiten explicar el aumento de la violencia. La inseguridad en la región tiene una explicación multidimensional en la que inciden la precariedad del empleo, la inequidad persistente y la insuficiente movilidad social (PNUD, 2013). Esta amalgama de factores indicen directamente en cómo se deben analizar los fenómenos desde una perspectiva holística.

#### Pobreza, desigualdad del ingreso y desempleo

No explican satisfactoriamente los niveles de inseguridad de la región, por ello, se requiere aceptar que la violencia y el delito no tienen explicaciones simples (PNUD, 2013). Estos problemas deben ser analizados al nivel más pequeño o local posible, como el barrio o hasta la cuadra, para entender las dinámicas sociales que implican estas causas.

#### Delito aspiracional

Según Robert Merton (1957), citado en el informe, desarrollo humano de América Latina, que en algunos ámbitos, surgen individuos o grupos dispuestos a desafiar el orden legítimo y optan por la vía delictiva como forma de vida, entonces, podríamos decir que un individuo delincuente actúa en pro de satisfacer las expectativas de consumo que demanda la sociedad y que no pueden ser satisfechas por las posibilidades laborales a las que tiene acceso.

### Vulnerabilidades institucionales

Los ciudadanos tendrán más incentivos de respetar las leyes establecidas, si consideran que su aplicación es justa, proporcional al delito, y respetuosa de los derechos humanos y del Estado de Derecho, pero los Estados tienen debilidades para proveer seguridad ciudadana. Una de las principales vulnerabilidades es la corrupción que fue analizada anteriormente; por ello, se explicarán la impunidad y la falta de proporcionalidad en el castigo.

#### Impunidad, desconfianza generalizada y tasa de no denuncia.

Aunque ningún país del mundo resuelve todos los crimines ni castiga a todos los delincuentes, hay un umbral mínimo para que en la ciudadanía no se cree una confianza generalizada, el temor o, incluso, el rechazo hacia la ley. Cuanto más grave el delito mayor debería ser la probabilidad de ser castigado, la cifra oculta es la tasa de no denuncia que se refleja en las encuestas de victimización (PNUD, 2013). Asimismo, esta cifra demuestra la confianza que tiene la comunidad en sus autoridades que, va en la denuncia como principal vehículo para llegar a la justicia.

#### Falta de proporcionalidad en el castigo y concentración en personas fáciles de detener.

Todo castigo debe ser proporcional a la gravedad del delito. Elena AZAOLA, Marcelo BERGAM y de acuerdo a lo citado en el Informe de Desarrollo Humano (2013), para América Latina, explican que el problema es que las policías, los fiscales y los jueces tienden a concertarse en la detención y en la sanción de personas que son fáciles de detener, en vez de hacerlo con criminales organizados que requieren mayor labor de inteligencia y coordinación interinstitucional.

+----------------------------------+--------------------------------------------------------------------------------------------+
| Causa estructural                | Factor                                                                                     |
+==================================+============================================================================================+
| Inseguridades invisibles         | -   Discriminación                                                                         |
|                                  |                                                                                            |
|                                  | -   Jóvenes y niños excluidos                                                              |
|                                  |                                                                                            |
|                                  | -   Violencia contra las mujeres                                                           |
+----------------------------------+--------------------------------------------------------------------------------------------+
| Corrupción                       | -   Poderes fácticos                                                                       |
|                                  |                                                                                            |
|                                  | -   Grandes desfalcos                                                                      |
|                                  |                                                                                            |
|                                  | -   Corrupción gris                                                                        |
|                                  |                                                                                            |
|                                  | -   Penetración del crimen organizado                                                      |
+----------------------------------+--------------------------------------------------------------------------------------------+
| Impacto de la globalización      | -   Económica                                                                              |
|                                  |                                                                                            |
|                                  | -   Política                                                                               |
|                                  |                                                                                            |
|                                  | -   Cultural                                                                               |
+----------------------------------+--------------------------------------------------------------------------------------------+
| Desajustes internos              | -   Semillero                                                                              |
|                                  |                                                                                            |
|                                  | -   Ocasión                                                                                |
|                                  |                                                                                            |
|                                  | -   Contexto                                                                               |
+----------------------------------+--------------------------------------------------------------------------------------------+
| Factores socio económicos        | -   Pobreza, desigualdad del ingreso y desempleo                                           |
|                                  |                                                                                            |
|                                  | -   Delito aspiracional                                                                    |
+----------------------------------+--------------------------------------------------------------------------------------------+
| Vulnerabilidades institucionales | -   Impunidad, desconfianza generalizada y tasa de no denuncia                             |
|                                  |                                                                                            |
|                                  | -   Falta de proporcionalidad en el castigo y concentración en personas fáciles de detener |
+----------------------------------+--------------------------------------------------------------------------------------------+

: Causas estructurales de la violencia y el delito

## Crisis y situaciones de vulnerabilidad

El concepto de "crisis" implica que la continuidad de un proceso -como tendencia y orientación intelectual- se ve amenazada, paulatina o bruscamente, hasta detenerse, bloquearse o desequilibrarse; esta nueva situación de urgencia abre un paréntesis de incertidumbre intenso que incide sobre los implicados y decisores al punto de apremiarlos para resolverla (Calderón, 2012). Las crisis pueden ser económicas, políticas, de la institucionalidad, sociales, humanitarias, diplomáticas, ambientales o de orden público, por nombrar algunas, que de igual forma provienen de diversas fuentes cómo conflictos, situaciones o problemas.

La PDH es fundamental en el establecimiento y protección del Estado de Derecho, se tomarán tres momentos de una crisis: el antes, el durante y el después; antes de una crisis se atacan las causas de la violencia y el delito, y se entendió que la zona o situación está en su normal actuar; durante una crisis, que puede ser ocasionada por un conflicto social o un desastre natural, la PDH debe atender la crisis y usar la cercanía con la comunidad, para guiarla en la respuesta, y, después de una crisis, la PDH debe restablecer el Estado de Derecho y crear resiliencia.

El Estado de Derecho implica que todos los ciudadanos estén sometidos a la Ley y que las leyes vigentes sean justas, no discriminatorias y que respeten los derechos humanos (PNUD, 2012). Pero en zonas de crisis y situación de vulnerabilidad el Estado de Derecho es a menudo profundamente socavado, y la injusticia e inseguridad florecen. En países inmersos en conflictos armados, mujeres y niños son objetos de violencia sexual y amplios segmentos de la sociedad son privados de sus más básicos derechos humanos (UNDP, 2011). En ese sentido, la PDH debe fortalecer, proteger y restablecer, cuando sea el caso, el Estado de Derecho, para que la ciudadanía pueda llevar a cabo su desarrollo humano, mediante unas condiciones adecuadas de seguridad ciudadana.

La crisis, la violencia y el delito comparten o tienen en común las mismas o algunas causas como la desigualdad, discriminación, violencia contra las mujeres y niños, impunidad y corrupción. Los programas del Estado de Derecho han aumentado la protección fiscal y legal de las personas y comunidades, asegurando la representación legal, acceso a la justicia, y empoderamiento de los individuos y la sociedad civil (UNDP, 2011). Así, la PDH debe atender estas causas en la lógica de satisfacer las necesidades básicas de cada persona en seguridad ciudadana. Por ejemplo: una ciudadana que trabaja en el centro de la ciudad y debe ir muy elegante a su trabajo, puesto que está encargada de las relaciones públicas de su empresa, confía que no le roben sus aretes de oro y celular en el servicio de transporte público.

Por lo tanto, la PDH no debe solo patrullar para disuadir el delincuente, sino entender las causas por las que una persona está delinquiendo en ese sector y más aún cuando ocurre una crisis. Esto puede ocurrir porque quien roba es un adicto y necesita dinero para comprar drogas, o es un desplazado por la violencia ocasionada por el conflicto interno, que necesita llevar dinero a casa para sus hijos y no tiene ayuda del Estado, a causa de la corrupción. Son muchos factores para un solo hecho, pero, allí está, que las soluciones de prevención son más complejas que las de "mano dura" que sería tan solo capturarlo y llevarlo al sistema judicial para que posiblemente lo detengan y deje completamente desprotegida su familia. Hasta en las crisis se necesitan soluciones de "mano inteligente".

Se puede decir que el Punto Focal Global (en inglés Global Focal Point) de Naciones Unidas, está alineado con el Programa Global de Fortalecimiento del Estado de Derecho, en Zonas de Crisis y Situaciones de Fragilidad del PNUD (organismo más representativo en ALC de desarrollo humano), así, la ONU dispone que esta organización debe hacer equipo con gobiernos nacionales interesados en construir instituciones de justicia y seguridad, que presten servicios para las comunidades e individuos, a través de un completo soporte al Estado de Derecho. Este programa global se enfoca en cuatro áreas claves, para establecer el Estado de Derecho, después de la crisis y el conflicto, que son afines con la PDH.

### Hacer frente al legado de la violencia

Después de violencia a gran escala, conflicto o inestabilidad política se busca soportar prácticas de justicia transicional contribuyentes a la reparación de la violencia pasada y la violación de derechos humanos para poder facilitar la responsabilidad del Estado.

Fortalecer la confianza, estableciendo las condiciones para la paz y la gobernanza democrática, y ayudar a las sociedades a protegerse contra la reactivación de la discriminación y/o violencia sistemática (UNDP, 2014), situación que entra como prioridad de la PDH, puesto que esta violencia puede continuar a través de los delitos.

### Incrementar la seguridad y protección para todos

Altos niveles de violencia armada e inseguridad, de forma continua, inhiben el desarrollo en muchos contextos, aun en la ausencia de conflicto o de elevados niveles de crimen violento, generan un impacto destructivo. La ausencia de seguridad en estos contextos puede perpetuar la falta de confianza entre las personas, comunidades y el Estado; por ello, se busca involucrar a la comunidad en la identificación de causas de inseguridad y hacer frente a ellas, enfatizando en la protección de las mujeres (UNDP, 2011), dado que la mujer ha sido históricamente más vulnerable ante los conflictos, por su rol social, ello en su condición de vulnerabilidad.

### Construir confianza por medio de instituciones accesibles y efectivas de justicia y seguridad

En contextos afectados por la crisis es prioridad restablecer rápidamente la justicia y la seguridad ciudadana a nivel nacional y local para la población. Se debe buscar con las autoridades, identificar e implementar reformas de mediano y largo plazo en justicia y seguridad, las cuales están alineadas con las prioridades nacionales y que quedan a cargo de las partes interesadas nacionales, también se busca desarrollar todo el sector de justicia y las estrategias de seguridad ciudadana (UNDP, 2014), y vincular los diversos actores como el sector empresarial y productivo.

### Mejorar la administración de justicia y seguridad para la mujer

La escalada del conflicto, típicamente, empeora los niveles de la violencia sexual basada en género, estos crímenes tienen un efecto nefasto a largo plazo en las victimas, sus familias y las comunidades donde viven. Se quiere proteger y fortalecer a la mujer en contextos de afectación de crisis por medio del acceso al servicio de justicia y seguridad ciudadana, y atacar la impunidad de la violencia sexual o basada en género. Por otro lado, se debe incrementar la participación y liderazgo de la mujer en las instituciones de seguridad y justica, e involucrar las comunidades con el fin de aumentar la prevención y conciencia de que el problema no es un asunto exclusivo de las mujeres, sino también los hombres, para combatir este tipo de violencia (UNDP, 2014) además, concientizar a la sociedad en general por lo que representa la mujer, constructora de tejido social y base familiar.

## Acerca de la (in)seguridad

Desde la perpectiva de la seguridad humana, en su dimesnión de seguridad personal, amplía el concepto de seguridad seguridad ciudadana, como un bien público, se refiere a un orden ciudadano democrático que elimina las amenazas de la violencia en la población, y permite la convivencia segura y pacífica (luz, 2012). Es decir, una seguridad que apunta al desarrollo humano desde unas condiciones óptimas de convivencia.

Actualmente, la inseguridad debe integrar, entre sus prioridades, el impacto del crimen organizado, transnacional, en la seguridad ciudadana local de ALC, como D. Luz, indica que por su capacidad corruptora, por su relación con el tráfico de drogas y por su capacidad de violencia, en particular a través del tráfico de armas, en américa latina y el caribe.

Las falencias en la reducción de las causas estructurales de la violencia y el delito generan la inseguridad, que es la principal amenaza para la estabilidad, el fortalecimiento democrático y las posibilidades de desarrollo humano (Secretaría General OEA, 2008), así mismo, la seguridad permite la ampliación de opciones de vida y libertad efectiva de las personas, independientemente de sus circunstancias (PNUD, 2009). La preocupación por la seguridad se ha convertido en uno de los principales motores de transformación de las ciudades latinoamericanas, causado por los pobres resultados en el control de la violencia y el delito, pues deja de lado los efectos reales de las políticas de seguridad a la seguritización (sAntillán, 2012), y recuerda que la región de América Latina y el Caribe posee unos índices de violencia bastante elevados.

La mano dura, puede ser entendida como una estrategia represiva de la seguridad ciudadana; y la seguritización, expresa que los problemas sociales, deben ser atendidos desde un ámbito de las políticas e instituciones de seguridad, y dejando de lado la causa social que las genera. Como lo expresa sAntillán (2012), son diversas tácticas de control del delito legitimadas en tanto están orientadas a producir seguridad, bajo esta lógica, la seguridad se entiende como un fin en sí misma que esta incluso por encima de los derechos, se puede relacionar la idea del intercambio de libertades por seguridad relacionado en el informe de desarrollo humano del Caribe. Así mismo la seguritización convierte los problemas sociales en problemas de seguridad, por ejemplo: en el narcotráfico de estupefacientes, todavía prima la concepción de un problema de seguridad, antes que pudiese ser un problema de salud pública o de educación.

Dentro de los cambios, identificados por Santillán, relacionados con la seguritización, se encuentran: la recuperación de espacios a través de la renovación urbana, que desplazan la delincuencia hacia otros lugares; la oferta inmobiliaria hacia conjuntos y barrios cerrados, llamado el "amurallamiento urbano"; y el control territorial a través de militares y grupos policiales, especializados, debido a la alta inseguridad.

También, han cambiado las formas de interacción social, debido a los comportamientos, de autoprotección y "evitamiento" que ocasionan cambios de rutina; el desplazamiento urbano; aumento del "vigilantismo", mediante brigadas barriales que utilizan la fuerza y violencia para su protección, y deslegitiman el monopolio del uso de la fuerza del Estado; y la estigmatización social, donde minorías étnicas, jóvenes o inmigrantes, son considerados la fuente de la inseguridad (sAntillán, 2012). Todo lo anterior se convierte en un abanico de opciones que evidencian la negligencia en la solución de problemas de seguridad ciudadana por parte de la política pública.

Los cuerpos de policía son unos de los principales responsables de la operacionalización y articulación de las políticas públicas, para contrarrestar la (in)seguridad, esta última se puede clasificar en (PNUD, 2009):

-   Objetiva: usar los datos pasados, como el comportamiento estadístico, para proyectar el riesgo futuro, y se refleja el grado de seguridad o inseguridad.

-   Subjetiva: es la percepción que cada persona tiene sobre el nivel de riesgo al que está expuesto, y es influida por varios factores racionales e irracionales, consientes e inconscientes, entre los cuales cabe mencionar: el temperamento, la experiencia, los prejuicios la información "objetiva" y las opiniones de los demás.
