# Contrarrestar la sofisticación y violencia del crimen organizado

Todos los delitos ocurren en circunstancias de modo, tiempo y lugar diferentes, pero cada delincuente u organización criminal tiene un nivel de conocimiento y experticia que determina la complejidad y sofisticación; en el mismo sentido, la violencia ejercida para cometer un delito es diferente en cada caso, así como las secuelas en las personas, estas se pueden interpretar como la violencia afecta el normal transcurrir de la vida.

Por ello, como se dijo, no se pueden considerar que todos los delincuentes son iguales, que el daño a la sociedad sea el mismo y que en las estadísticas operativas policiales sumen igual.

Esto se puede explicar a través de redes criminales, que se entiende como un conjunto de nodos (actores criminales) y enlaces (relaciones entre ellos) que se encuentran en un conjunto de datos, cuyo principal objetivo es obtener dinero a través de actividades ilegales en un lugar geográfico.

Según lo anterior, y sin querer entrar en el ámbito penal sino en términos policiales, se proponen escalas de sofisticación criminal y de violencia, para orientar los esfuerzos de la PDH, con el fin capturar los criminales más sofisticados y violentos dentro de una red criminal; el sistema judicial se encargara de establecer los tipos penales.

## Variables de la sofisticación criminal

Se propone una escala de cinco niveles, en el que es el menos sofisticado y cinco el más sofisticado, para ello se tendrá en cuenta variables de complejidad, así:

**Adaptación de tecnología:** relacionado con las innovaciones tecnológicas usadas para la actividad criminal.

**Conocimiento de la actividad criminal:** experiencia en la realización y planeación de delitos.

**Gestión organizacional:** el diseño de metas, creación de una estructura criminal, vinculación de personal, diseño de procesos y financiamiento de las actividades criminales.

**Capacidad para eludir la captura:** relacionada con la for- ma de escapar de la actuación policial, la investigación criminal, y la utilización de herramientas jurídicas para cuando se es capturado; al igual que la utilización de la corrupción para tales fines.

**Adaptación de otras actividades criminales:** en este se considera la diversificación del portafolio criminal, pues al sofisticarse tiene más poder criminal y económico, y esto requiere vincular otras actividades criminales.

**Impacto en la seguridad objetiva:** la incidencia en los indicado- res de seguridad ciudadana y su participación en el número de delitos.

**Impacto en la seguridad subjetiva:** las actividades criminales inciden en la percepción de seguridad y en la cooperación con las autoridades, también si estas actividades producen desplazamientos y cambios de rutinas.

## Escala de sofisticación criminal

Se aspira que la escala permita clasificar a los delincuentes que se persiguen, diseñar tácticas para su captura y priorizar aquellos que la comunidad requiere; puede ocurrir que un delincuente tenga variables de complejidad de diferentes niveles, lo cual permitirá un análisis más apropiado para orientar la labor policial.

A continuación se presentará la escala de cinco niveles de sofisticación criminal, estos niveles de las redes se identifican a través de aprendizaje no supervisado o métodos que permiten extraer información de los datos sin entrenar un modelo con datos etiquetados, es decir, no conocemos la respuesta.

### Nivel 1. Redes inexpertas

En este nivel, el crimen es una opción sea cual sea la motivación, sin conocer ampliamente cómo se mueve el mundo criminal, los riesgos, ventajas y desventajas; se decide cometer crímenes, puede hacerse como "propio negocio" al sirviendo de otro. Igualmente, incluyen los criminales circunstanciales que solo cometieron algún crimen de manera esporádica y no reinciden sistemáticamente (berniell, 2014); desde este nivel, se focaliza en la persona y su evolución en su carrera criminal, pero no desde la perspectiva del fenómeno criminal.

+--------------------------------------------+---------------------------------------------------------------------------------+
| Variables de sofisticación                 | Características                                                                 |
+============================================+=================================================================================+
| Adaptación de tecnología                   | -   Uso escaso de la tecnología                                                 |
|                                            |                                                                                 |
|                                            | <!-- -->                                                                        |
|                                            |                                                                                 |
|                                            | -   Utiliza principalmente su cuerpo y estado físico para los crímenes          |
|                                            |                                                                                 |
|                                            | -   Aprovecha el factor sorpresa principalmente                                 |
+--------------------------------------------+---------------------------------------------------------------------------------+
| Conocimiento de la actividad criminal      | -   Se inicia a delinquir                                                       |
|                                            |                                                                                 |
|                                            | -   Etapa de descubriendo del mundo criminal                                    |
|                                            |                                                                                 |
|                                            | -   Identificación de ventajas y oportunidades propias                          |
|                                            |                                                                                 |
|                                            | -   No tiene una actividad criminal definida                                    |
+--------------------------------------------+---------------------------------------------------------------------------------+
| Gestión organizacional                     | -   Poco personal participa en las actividades                                  |
|                                            |                                                                                 |
|                                            | -   Contactos muy limitados a los que acudir para realizar los delitos          |
|                                            |                                                                                 |
|                                            | -   No tiene una estructura para gestionar los crímenes                         |
|                                            |                                                                                 |
|                                            | -   No posee metas y objetivos criminales                                       |
+--------------------------------------------+---------------------------------------------------------------------------------+
| Capacidad para eludir la captura           | -   Fácil de identificar y detener por las autoridades                          |
|                                            |                                                                                 |
|                                            | -   Puede ser detenido en flagrancia                                            |
|                                            |                                                                                 |
|                                            | -   Desconoce cómo evitar el accionar policial                                  |
+--------------------------------------------+---------------------------------------------------------------------------------+
| Adaptación de otras actividades criminales | -   Realiza una única actividad criminal                                        |
|                                            |                                                                                 |
|                                            | -   No tiene la capacidad para adaptar otras                                    |
|                                            |                                                                                 |
|                                            | -   Desconoce que otras actividades criminales puede adaptar                    |
+--------------------------------------------+---------------------------------------------------------------------------------+
| Impacto en la seguridad objetiva           | -   No tiene participación porcentual en los indicadores de seguridad ciudadana |
|                                            |                                                                                 |
|                                            | -   Los delitos son cometidos muy esporádicamente                               |
|                                            |                                                                                 |
|                                            | -   Por el tipo de delito y la cuantía se instauran pocas denuncias             |
|                                            |                                                                                 |
|                                            | -   Su zona de actuar se da como un punto caliente                              |
+--------------------------------------------+---------------------------------------------------------------------------------+
| Impacto en la seguridad subjetiva          | -   Afecta a un grupo pequeño de personas                                       |
|                                            |                                                                                 |
|                                            | -   Baja incidencia en la percepción de seguridad en una zona                   |
|                                            |                                                                                 |
|                                            | -   Baja influencia en las encuestas de victimización                           |
|                                            |                                                                                 |
|                                            | -   No son delincuentes reconocidos o temidos                                   |
+--------------------------------------------+---------------------------------------------------------------------------------+

: Característica red criminal inexperta

### Nivel 2. Redes perseverantes

Desde este nivel, las personas reinciden sistemáticamente en la comisión de delitos y empiezan a ver la delincuencia como opción de vida; ya no son criminales circunstanciales y tienen una motivación personal y/o económica.

+--------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Variables de sofisticación                 | Características                                                                                              |
+============================================+==============================================================================================================+
| Adaptación de tecnología                   | -   El delito es realizado con el uso de tecnología de fácil acceso                                          |
|                                            |                                                                                                              |
|                                            | <!-- -->                                                                                                     |
|                                            |                                                                                                              |
|                                            | -   Sabe cómo y donde adquirir la tecnología                                                                 |
|                                            |                                                                                                              |
|                                            | -   Conoce las limitaciones y daños que causa la misma                                                       |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Conocimiento de la actividad criminal      | -   Diseña planes simples                                                                                    |
|                                            |                                                                                                              |
|                                            | -   Analiza la presencia policial                                                                            |
|                                            |                                                                                                              |
|                                            | -   Identifica las mejores zona para su actividad criminal                                                   |
|                                            |                                                                                                              |
|                                            | -   Identifica las mejores víctimas                                                                          |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Gestión organizacional                     | -   Coordina actividades criminales con otros                                                                |
|                                            |                                                                                                              |
|                                            | -   Posee contactos e informantes para llevar a cabo el crimen                                               |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Capacidad para eludir la captura           | -   Prevé rutas de escape                                                                                    |
|                                            |                                                                                                              |
|                                            | -   Tiene una historia preparada para las autoridades                                                        |
|                                            |                                                                                                              |
|                                            | -   Captura en flagrancia más complicada                                                                     |
|                                            |                                                                                                              |
|                                            | -   Requiere una investigación criminal a corto plazo para su captura                                        |
|                                            |                                                                                                              |
|                                            | -   Inicia a tener nociones jurídicas un porqué puede ser capturado                                          |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Adaptación de otras actividades criminales | -   Identifica las actividades criminales acordes a su portafolio criminal                                   |
|                                            |                                                                                                              |
|                                            | -   Intimida a sus víctimas o las deja en situación de indefensión                                           |
|                                            |                                                                                                              |
|                                            | -   Comete diferentes delitos así no tengan conexión                                                         |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Impacto en la seguridad objetiva           | -   Afecta los indicadores de seguridad ciudadana de un pequeño sector o actividad criminal                  |
|                                            |                                                                                                              |
|                                            | -   Se considera como alguien reconocido del sector o la actividad criminal                                  |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| Impacto en la seguridad subjetiva          | -   Las encuestas de victimización se ven afectadas en poco porcentaje en las zonas donde delinque           |
|                                            |                                                                                                              |
|                                            | -   Su estilo criminal está siendo conocido                                                                  |
|                                            |                                                                                                              |
|                                            | -   Inicia a efectuar rutinas como cambiar de ruta, los transeúntes no vestir elementos de valor en la calle |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------+

: Característica red criminal perseverante

### Nivel 3. Redes experimentadas

Se puede decir que es un criminal de carrera, tiene la suficiente experiencia y conocimiento para medir riesgos, planear, influenciar otros para que le sirvan y llevar a cabo acciones criminales más violentas, arriesgadas y en escala, para obtener más ganancia y poder.

+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Variables de sofisticación                 | Características                                                                                                                    |
+============================================+====================================================================================================================================+
| Adaptación de tecnología                   | -   Posee una infraestructura tecnológica para llevar a cabo los crímenes                                                          |
|                                            |                                                                                                                                    |
|                                            | <!-- -->                                                                                                                           |
|                                            |                                                                                                                                    |
|                                            | -   Utiliza medios de transporte                                                                                                   |
|                                            |                                                                                                                                    |
|                                            | -   Utiliza tecnologías de la información y la comunicación                                                                        |
|                                            |                                                                                                                                    |
|                                            | -   Tiene acceso a armas de fuego y blindajes                                                                                      |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Conocimiento de la actividad criminal      | -   Conoce las fallas y vacíos jurídicos del sistema penal                                                                         |
|                                            |                                                                                                                                    |
|                                            | -   Deslegitima los procedimientos policiales                                                                                      |
|                                            |                                                                                                                                    |
|                                            | -   Conoce rutinas y capacidades de los cuerpos de policía                                                                         |
|                                            |                                                                                                                                    |
|                                            | -   Identifica quienes son los grandes líderes de las actividades criminales                                                       |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Gestión organizacional                     | -   Los planes que realiza son complejos, involucran tiempos, movimientos, personas y un grado alto de coordinación y comunicación |
|                                            |                                                                                                                                    |
|                                            | -   Maneja estructuras de cobertura en el ámbito local o regional                                                                  |
|                                            |                                                                                                                                    |
|                                            | -   Su estructura criminal tiene niveles jerárquicos y roles claros                                                                |
|                                            |                                                                                                                                    |
|                                            | -   Diseñan metas y mediciones                                                                                                     |
|                                            |                                                                                                                                    |
|                                            | -   Existe un proceso de toma de decisiones                                                                                        |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Capacidad para eludir la captura           | -   Es reconocido en el mundo criminal y policial                                                                                  |
|                                            |                                                                                                                                    |
|                                            | -   La captura en flagrancia es improbable y requiere invesygaciones criminales complejas                                          |
|                                            |                                                                                                                                    |
|                                            | -   Jurídicamente es difícil completar un proceso, solamente cuando es delatado                                                    |
|                                            |                                                                                                                                    |
|                                            | -   Tiene muchos lugares y amigos donde esconderse                                                                                 |
|                                            |                                                                                                                                    |
|                                            | -   Sigue dejando rastro de su vinculación a los crímenes                                                                          |
|                                            |                                                                                                                                    |
|                                            | -   Inicia a corromper funcionarios públicos                                                                                       |
|                                            |                                                                                                                                    |
|                                            | -   Perdió el miedo por las autoridades, pues ha escapado de ellas                                                                 |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Adaptación de otras actividades criminales | -   Tiene diferentes actividades criminales asociadas                                                                              |
|                                            |                                                                                                                                    |
|                                            | -   Puede controlar e iniciar a combinar diferentes actividades criminales                                                         |
|                                            |                                                                                                                                    |
|                                            | -   Es buscado por otros delincuentes para ayudar a la realización de crímenes                                                     |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Impacto en la seguridad objetiva           | -   Afecta significativamente las estadísticas delincuenciales locales o regionales                                                |
|                                            |                                                                                                                                    |
|                                            | -   Está en las prioridades policiales de una localidad o ciudad                                                                   |
|                                            |                                                                                                                                    |
|                                            | -   Aparece en diferentes índices criminales                                                                                       |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Impacto en la seguridad subjetiva          | -   Los ciudadanos conocen quién los está afectando                                                                                |
|                                            |                                                                                                                                    |
|                                            | -   Cambia rutinas de los ciudadanos y estigmatizan lugares y horarios                                                             |
|                                            |                                                                                                                                    |
|                                            | -   Es reconocido su *modus operandi*                                                                                              |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+

: Característica red criminal experimentada

### Nivel 4. Redes renovadoras

Por decirlo así es un criminal exitoso, pero quiere más poder y dinero, no se limita con lo que ha logrado, entonces, se le llama renovador porque busca impulsar más su carrera criminal llega hasta crímenes internacionales, más violentos y quiere manejar grandes estructuras del crimen.

+--------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Variables de sofisticación                 | Características                                                                                                                           |
+============================================+===========================================================================================================================================+
| Adaptación de tecnología                   | -   Acceso total a la tecnología requerida para sus actividades criminales                                                                |
|                                            |                                                                                                                                           |
|                                            | <!-- -->                                                                                                                                  |
|                                            |                                                                                                                                           |
|                                            | -   Adquiere tecnología de alto costo                                                                                                     |
|                                            |                                                                                                                                           |
|                                            | -   Innova tecnológicamente                                                                                                               |
+--------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Conocimiento de la actividad criminal      | -   Manipula el sistema judicial para adaptar sus actividades criminales al marco jurídico existente                                      |
|                                            |                                                                                                                                           |
|                                            | -   Su planeación es estratégica, continua y trascendente en el tiempo                                                                    |
|                                            |                                                                                                                                           |
|                                            | -   Conoce el funcionamiento, debilidades y niveles de la Policía y los entes de control nacional e internaciona                          |
|                                            |                                                                                                                                           |
|                                            | -   Innova en la forma de realizar los delitos                                                                                            |
|                                            |                                                                                                                                           |
|                                            | -   Conoce cómo funciona un diverso grupo de actividades criminales                                                                       |
+--------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Gestión organizacional                     | -   Maneja estructuras de influencia a nivel nacional y en algunos casos internacional                                                    |
|                                            |                                                                                                                                           |
|                                            | -   Muy posiblemente es la cabeza de la organización criminal o está en su nivel jerárquico más alto                                      |
|                                            |                                                                                                                                           |
|                                            | -   Existe una estructura organizacional sólida                                                                                           |
|                                            |                                                                                                                                           |
|                                            | -   Existen relevos de líderes                                                                                                            |
|                                            |                                                                                                                                           |
|                                            | -   La estructura de poder, mando y justicia dentro de la organización criminal, está bien definida                                       |
+--------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Capacidad para eludir la captura           | -   Puede ser considerado invisible en muchos delitos                                                                                     |
|                                            |                                                                                                                                           |
|                                            | -   Se sabe que ha participado en delitos, pero no se puede vincular a las investigaciones                                                |
|                                            |                                                                                                                                           |
|                                            | -   Mediante arduas labores se de inteligencia e investigación criminal, de largo plazo, puede llegar a su captura                        |
|                                            |                                                                                                                                           |
|                                            | -   Puede cambiar su apariencia y evitar los sistemas de identificación                                                                   |
|                                            |                                                                                                                                           |
|                                            | -   Lleva a la corrupción miembros de la policía y autoridades políticas de alto nivel                                                    |
|                                            |                                                                                                                                           |
|                                            | -   Se ofrecen recompensas para su captura                                                                                                |
+--------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Adaptación de otras actividades criminales | -   No se focaliza en un delito principal, sino ha adaptado diversas actividades criminales que lo mantienen vigente en el mundo criminal |
|                                            |                                                                                                                                           |
|                                            | -   Reconocimiento por manejar un amplio portafolio criminal                                                                              |
|                                            |                                                                                                                                           |
|                                            | -   Vincula diferentes delitos para su fin económico                                                                                      |
|                                            |                                                                                                                                           |
|                                            | -   La violencia puede estar presente en gran número de actividades criminales                                                            |
|                                            |                                                                                                                                           |
|                                            | -   Asocia algunas actividades criminales con actividades legales                                                                         |
+--------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Impacto en la seguridad objetiva           | -   Responsable de forma directa por la afectación de varios indicadores de seguridad ciudadana                                           |
|                                            |                                                                                                                                           |
|                                            | -   Cobertura de delitos a nivel nacional e internacional                                                                                 |
|                                            |                                                                                                                                           |
|                                            | -   Puede ser el principal actor criminal en un delito o varios delitos                                                                   |
+--------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Impacto en la seguridad subjetiva          | -   Posee zonas de influencia donde existe temor                                                                                          |
|                                            |                                                                                                                                           |
|                                            | -   Influye la no denuncia o colaboración a las autoridades                                                                               |
|                                            |                                                                                                                                           |
|                                            | -   Afecta la tasa de victimización ampliamente                                                                                           |
|                                            |                                                                                                                                           |
|                                            | -   La percepción de seguridad se ve reducida                                                                                             |
|                                            |                                                                                                                                           |
|                                            | -   Afecta negativamente la confianza en la eficacia de las autoridades policiales y del Estado                                           |
+--------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+

: Característica red criminal renovadora

### Nivel 5. Redes expertas

Este nivel se enfoca en la búsqueda del poder criminal y el control territorial, y buscan usar la corrupción como elemento criminal. Son buscados y reconocidos en otros países, se generan unas barreras de entrada a las actividades criminales de su indecencia. Al poseer más poder económico y criminal puede sofisticarse más rápido y mejor, y tiene la innovación como uno de sus prioridades.

+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| Variables de sofisticación                 | Características                                                                                                        |
+============================================+========================================================================================================================+
| Adaptación de tecnología                   | -   Financia investigaciones, desarrollos tecnológicos y estudios, para mejorar su producción criminal                 |
|                                            |                                                                                                                        |
|                                            | <!-- -->                                                                                                               |
|                                            |                                                                                                                        |
|                                            | -   Realiza experimentos científicos                                                                                   |
|                                            |                                                                                                                        |
|                                            | -   Las autoridades desconocen qué tecnologías está usando                                                             |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| Conocimiento de la actividad criminal      | -   Puede influenciar la creación de normatividad que le favorezca para su actividad criminal                          |
|                                            |                                                                                                                        |
|                                            | -   Innova en las tipologías criminales                                                                                |
|                                            |                                                                                                                        |
|                                            | -   Innova en los procesos o rutas de un delito                                                                        |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| Gestión organizacional                     | -   Maneja varias organizaciones criminales                                                                            |
|                                            |                                                                                                                        |
|                                            | -   Influye en otras organizaciones y en la forma de cometer delitos                                                   |
|                                            |                                                                                                                        |
|                                            | -   Puede manejar un mercado criminal                                                                                  |
|                                            |                                                                                                                        |
|                                            | -   Puede decidir o autorizar donde y cuando se cometen los delitos                                                    |
|                                            |                                                                                                                        |
|                                            | -   Influencia entes gubernamentales para sus necesidades                                                              |
|                                            |                                                                                                                        |
|                                            | -   Cuenta con un gran número de asesores en diferentes áreas                                                          |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| Capacidad para eludir la captura           | -   Tiene la capacidad para llevar la corrupción a varios servidores públicos en diferentes niveles jerárquicos        |
|                                            |                                                                                                                        |
|                                            | -   Cuando es capturado, puede acudir a expertos del derecho para tener una fuerte defensa                             |
|                                            |                                                                                                                        |
|                                            | -   Se ofrecen grandes recompensas por información que conduzca a su captura                                           |
|                                            |                                                                                                                        |
|                                            | -   La investigación judicial la realizan grupos muy especializados                                                    |
|                                            |                                                                                                                        |
|                                            | -   Puede llegar a negociar grandes rebajas de penas por la información que posee                                      |
|                                            |                                                                                                                        |
|                                            | -   Puede que no apareza en bases de datos o investigaciones criminales                                                |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| Adaptación de otras actividades criminales | -   Su portafolio criminal es muy amplio va y desde actividades simples hasta muy especializadas                       |
|                                            |                                                                                                                        |
|                                            | -   La trazabilidad de las actividades criminales es muy compleja                                                      |
|                                            |                                                                                                                        |
|                                            | -   Asocia gran número de actividades criminales con actividades legales                                               |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| Impacto en la seguridad objetiva           | -   Difícil establecer su afectación real afectación en los índices criminales                                         |
|                                            |                                                                                                                        |
|                                            | -   Diversificación criminal muy amplia                                                                                |
|                                            |                                                                                                                        |
|                                            | -   Desconocimiento de todos los indicadores que afecta                                                                |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| Impacto en la seguridad subjetiva          | -   Es ampliamente conocido por la opinión pública o es completamente desconocido                                      |
|                                            |                                                                                                                        |
|                                            | -   Influencia negativa en la percepción de seguridad ciudadana en el ámbito local, regional, nacional e internacional |
|                                            |                                                                                                                        |
|                                            | -   Influencia para que las personas no denuncien                                                                      |
|                                            |                                                                                                                        |
|                                            | -   Puede poner en cuestionamiento la institucionalidad                                                                |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------+

: Característica red criminal experta

## Escala de violencia criminal

Como se definió al inicio del documento, la violencia es ese daño evolutivo de abuso de poder que se manifiesta en tres formas: física, sociológica y sexual, con el fin de ofrecer una definición para la actuación policial de las formas de violencia; nos basaremos en el "Protocolo sobre violencia física, psicológica y sexual en los centros educativos de secundaria" (Ministerio de Educación Pública, 2012), puesto que abarca desde el nivel más bajo de violencia hasta el más alto, así:

-   En el caso de la violencia física se reconoce una amplia gama de situaciones tales como: castigos corporales (golpes, azotes, pellizcos, palmadas, hasta lesiones personales o la muerte); permanencia forzada en lugares, encerramientos, inmovilizaciones o "amarramientos"; "ejercicios" físicos, individuales o colectivos, entre otros.

-   La violencia psicológica puede incluir desde chistes, burlas, humillaciones individuales o colectivas, segregación en la participación de actividades, limitación de derechos, palabras hirientes, grafitos, notas anónimas basadas en la discrimi- nación por origen nacional, étnico, preferencia sexual, de género, condición física o mental, amenazas, entre otras.

-   La violencia sexual incluye desde insinuaciones, tocamientos, relaciones sexuales desiguales o de poder, acoso, comentarios o insinuaciones verbales, gestos, corrupción, proxenetismo o violación, utilización de calificaciones con fines sexuales u otras promesas de ventajas económicas o de otra naturaleza, que incluyen la explotación sexual comercial, entre otras.

### Severidad y frecuencia de la violencia criminal

Se entiende la frecuencia de la violencia como un patrón repetitivo de maltrato que puede haber sido nunca, alguna vez, varias veces, muchas veces, y la severidad de la violencia que permite establecer la dimensión del daño físico y sicológico (vAldez, híjAr medinA, sAlGAdo de snyder, riverA, AvilA, & rojAs, 2006), que para este caso se establecerá mediante una escala de uno a cinco, en el que uno es la severidad más baja y cinco las más alta. En la matriz de nivel de violencia (ver tabla siguiente) se propone cómo articular estos tres elementos de la violencia (forma, frecuencia y severidad); en el caso de que la frecuencia sea nunca denota que no hay severidad, pues no ha habido un caso de violencia. Asimismo, en cada análisis se debe aumentar la prioridad de acciones en contra de la delincuencia cuando exístan varias víctimas, en niños, niñas y adolescentes o en poblaciones en estado de vulnerabilidad.

+-----------+--------------+---------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Severidad | Frecuencia   | Violencia física                                                    | Violencia psicológica                                                                            | Violencia sexual                                                           |
+===========+==============+=====================================================================+==================================================================================================+============================================================================+
| 1         | Muchas veces | Sin marcas pero se usa la violencia                                 | Amenazas o malos tratos no fuertes o que no afectan su desenvolvimiento social y calidad de vida | Obligación a ver o escuchar actos sexuales, pero sin ser tocado o agredido |
|           |              |                                                                     |                                                                                                  |                                                                            |
|           | Varias veces |                                                                     |                                                                                                  |                                                                            |
|           |              |                                                                     |                                                                                                  |                                                                            |
|           | Alguna vez   |                                                                     |                                                                                                  |                                                                            |
|           |              |                                                                     |                                                                                                  |                                                                            |
|           | Nunca        |                                                                     |                                                                                                  |                                                                            |
+-----------+--------------+---------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+
| 2         | Muchas veces | Marcas                                                              | Limitación                                                                                       | Acoso                                                                      |
|           |              | no permanentes que no afectan su vida diaria ni el disfrute de sus  | de derechos mediante acciones hirientes privadamente como                                        | sexual leve sin llegar al contacto físico y afectación del normal          |
|           | Varias veces | derechos                                                            | degradaciones, malos tratos o humillaciones que afectan la calidad de                            | desarrollo de su vida                                                      |
|           |              |                                                                     | vida                                                                                             |                                                                            |
|           | Alguna vez   |                                                                     |                                                                                                  |                                                                            |
|           |              |                                                                     |                                                                                                  |                                                                            |
|           | Nunca        |                                                                     |                                                                                                  |                                                                            |
+-----------+--------------+---------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+
| 3         | Muchas veces | Secuelas                                                            | Limitación                                                                                       | Acoso                                                                      |
|           |              | no permanentes pero que necesitan recuperación que le limitan el    | de derechos mediante la segregación de actividades, acciones                                     | sexual con contacto físico por cualquier medio utilizado sea               |
|           | Varias veces | disfrute de sus derechos por un periodo corto de tiempo             | hirientes públicamente como degradaciones, humillaciones que afectan                             | intimidación, indefensión o engaño                                         |
|           |              |                                                                     | la calidad de vida y su integración en el tejido social                                          |                                                                            |
|           | Alguna vez   |                                                                     |                                                                                                  |                                                                            |
|           |              |                                                                     |                                                                                                  |                                                                            |
|           | Nunca        |                                                                     |                                                                                                  |                                                                            |
+-----------+--------------+---------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+
| 4         | Muchas veces | Secuelas                                                            | Problemas                                                                                        | Obligación                                                                 |
|           |              | permanentes en su integridad física de                              | de salud mental, inseguridad o temor permanentes que afectan                                     | a prácticas sexuales sin consentimiento, usando                            |
|           | Varias veces | difícil recuperación, que afectan su vida diaria por un largo plazo | su vida diaria                                                                                   | la intimidación, indefensión o engaño                                      |
|           |              |                                                                     |                                                                                                  |                                                                            |
|           | Alguna vez   |                                                                     |                                                                                                  |                                                                            |
|           |              |                                                                     |                                                                                                  |                                                                            |
|           | Nunca        |                                                                     |                                                                                                  |                                                                            |
+-----------+--------------+---------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+
| 5         | Muchas veces | Muerte                                                              | Problemas                                                                                        | Explotación                                                                |
|           |              | o tortura                                                           | de salud mental permanentes con asistencia especializada o medicación                            | sexual comercial por obligación o engaño y poniendo en estado de           |
|           | Varias veces |                                                                     | permanente                                                                                       | indefensión a la persona                                                   |
|           |              |                                                                     |                                                                                                  |                                                                            |
|           | Alguna vez   |                                                                     |                                                                                                  |                                                                            |
|           |              |                                                                     |                                                                                                  |                                                                            |
|           | Nunca        |                                                                     |                                                                                                  |                                                                            |
+-----------+--------------+---------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+

: Escala de severidad y frecuencia de violencia criminal Algunas características para la violencia sexual fueron basadas del National Sexual Violence Resource Center (National Sexual Violence Resource Center -NSVRC, 2012)

La tabla anterior muestra desde la perspectiva policial los niveles y formas de violencia para prevenir y atacar, denotando que la PDH busca atacar las causas estructurales que la generan, pero sin descuidar los hechos que están ocurriendo con el fin contrarrestarlos.

La combinación de la escala sofisticación criminal con la escala de violencia criminal puede llegar a establecer los objetivos y metas más pertinentes de la PDH, se podría establecer quiénes serían los delincuentes y actividades delincuenciales prioritarias; es decir focalizar las actividades policiales, si es mas conveniente prevenir, disuadir, controlar o investigar; pero siempre atacando las causas estructurales para ir disminuyendo la violencia y el delito a largo plazo.