# Introducción

La agenda política en América Latina y el Caribe tiene entre sus prioridades la seguridad ciudadana como soporte del desarrollo humano, sin seguridad el desarrollo humano se reduce, aumenta la violencia y el delito, y todo sumado afecta negativamente otras variables o procesos económicos, sociales y políticos que desintegran el desarrollo en general y la condición y bienestar humano en especial como lo indica el [@hdr2009, pp. 29-31]. Esto quiere decir que sin condiciones necesarias en seguridad ciudadana no puede existir una mejora en la calidad de vida de las personas y en el desarrollo pleno de las capacidades personales.

En efecto, al poner en consideración la evaluación que ha tenido el concepto de seguridad desde 1994, cuando la Organización de Naciones Unidas cambió el paradigma y estableció la seguridad humana como la libertad de amenaza, riesgo, necesidad y miseria de las personas se observa que las agrupó en 7 dimensiones: seguridad personal, seguridad alimentaria, seguridad económica, seguridad de la salud, seguridad ambiental, seguridad comunal y seguridad política.

Así, cambió radicalmente la unidad de análisis en temas de seguridad y dejando de ser el territorio el eje seguridad nacional y se centró en la persona, en su sensación de temor y la forma en que actúa respecto a ello. De esta manera, se articuló el desarrollo humano y la seguridad ciudadana, pues al no haber armonía social, se debió abordar otro concepto de seguridad como lo es la seguridad pública, que busca fortalecer la capacidad de nuestros Estados para promover la seguridad ciudadana y para responder eficazmente a la inseguridad, la delincuencia y la violencia.

Para ello desde el concepto de seguridad pública, se debe adecuar según sea necesario, su marco jurídico, las estructuras, procedimientos operativos y mecanismos de gestión como lo indicó la [@oea2008, p. 86], entendida como un sistema desarrollado para entender la conflictividad social y su relación con el crimen.

El desarrollo humano consiste en que todos tengan las mismas oportunidades en la vida, implica no solo ampliar las capacidades para incrementar las opciones actuales de las personas llevar vidas sanas, productivas y seguras, sino también garantizar que estas opciones no pongan en peligro, ni restrinjan aquellas disponibles para las futuras generaciones [@hdr2014, p. 3-5].

La seguridad humana para el desarrollo humano no es una simple reducción de los índices del delito y la violencia, sino que es entendida como el resultado de una política que se oriente a una estrategia integral que mejore la calidad de vida de la población, que respete y proteja los derechos humanos, la acción comunitaria para la prevención del delito y la violencia; una justicia accesible, ágil y eficaz. Una educación que se base en valores de convivencia pacífica, respetuosa de la Ley, tolerante y en la construcción de la cohesión social (PNUD, 2013).

El Estado debe armonizar la seguridad nacional, que busca proteger de amenazas el sistema político y mantener su estabilidad (es más de corte militar); la seguridad pública, que indica que las amenazas de seguridad van más allá de la esfera militar tradicional e incluyen problemas que tienen un impacto directo en la vida de las personas, como son la violencia de pandillas, el crimen cibernético, el tráfico ilegal de drogas o de seres humanos (estaría más relacionado con el crimen organizado); y la seguridad ciudadana, que protege a las personas de la violencia y el delito, y asegura la convivencia ciudadana (es de enfoque policial principalmente), para diseñar políticas de seguridad humana que implica desplegar acciones integrales y coordinadas de toda la institucionalidad del Estado.

La Policía para el Desarrollo Humano (PDH), es un modelo propio desde la perspectiva de América Latina y el Caribe que aterriza la seguridad humana a los cuerpos de policía, alineado con la cuarta revolución industrial. Este modelo de policía se concibe como una filosofía y estrategia para la construcción activa de la seguridad entre la ciudadanía y el Estado, con enfoque en la solución de problemas y necesidades en microterritorios multicrimen, analizados a través de la ciencia de los datos e inteligencia artificial, para prevenir las crisis, las causas estructurales de la violencia y el delito; y así, mejorar el desarrollo humano, reducir las tasas de criminalidad y mantener el Estado de Derecho.

Por consiguiente, mediante la articulación de las conceptualizaciones de desarrollo humano, la seguridad humana y de la ciencia de los datos, este documento pretende plantear un modelo que permita establecer las tipologías de los cuerpos de policía en América Latina y el Caribe.

Entonces, 1) se centra conceptualmente la Policía para el Desarrollo Humano (PDH) desde los planteamientos actuales de la seguridad humana y el desarrollo humano; 2) se determinan los elementos claves para el análisis de los modelos existentes de policía en América Latina y el Caribe, 3) se establecen las dimensiones e indicadores de impacto intermedio, y 4) se utiliza la ciencia de los datos para la toma de decisiones anticipativas.

Desde el ámbito académico están integrar conocimientos accionables a la ciencia de policía al igual que proponer nuevas perspectivas de estudio, pues según la realidad de la región, la policía debe apuntar hacia el desarrollo humano, para reducir la violencia y el delito.

Para una perspectiva organizacional, se propone un modelo de análisis, organizacional para establecer qué tan preventivo es un cuerpo de policía, lo cual, podría ayudar a la toma de decisiones estratégicas. En relación con la política pública, ofrece ciertos elementos que pueden servir para el diseño de una política integral de seguridad ciudadana, desde la perspectiva de la glocalidad (piensa global y actúa local) para la solución articulada de problemáticas.

EN un enfoque de los cuerpos de policía, se brindan nuevas herramientas técnicas y epistemológicas, para mejorar la prestación del servicio de policía y la prevención de la violencia y el delito de forma articulada con todo el aparato estatal responsable de atender falencias sociales, fuente de las causas.

En el primer capítulo, se definirán la seguridad ciudadana, el desarrollo humano, la violencia y el delito para la presente investigación, igualmente, se identifican las causas estructurales de la violencia y el delito en el contexto de América Latina y el Caribe, al igual que características importantes relacionados con el desarrollo humano, en momentos de crisis.

El segundo capítulo articulará los conceptos de desarrollo humano y ciencia de policía, para proponer perspectivas y escenarios de análisis y de investigación para fortalecer estas aproximaciones teóricas. Allí se articulan los diferentes niveles de estado basados en problemáticas conjuntas, en un mundo de poder compartido. Por otro lado, también se incluyen aproximaciones del derecho de policía, policía comunitaria, y se define que es la Policía para el Desarrollo Humano y sus implicaciones en el servicio de policía, el ente policía y los cuerpos de policía.

El tercer capítulo, se basa en las dimensiones de impacto de la seguridad ciudadana, para generar desarrollo humano y propone indicadores de Policía para el Desarrollo Humano, con el fin de atacar las causas estructurales de la violencia y el delito, integrados con índice de desarrollo humano y sistema regional de indicadores Estandarizados de convivencia y Seguridad ciudadana (SES). Por otro lado, se proponen la escala de sofisticación criminal y la escala de violencia, desde una mirada policial.

El cuarto capítulo, aborda los conceptos de la lógica difusa aplicada a la Policía para el Desarrollo Humano, llegando a una aproximación de un sistema de inferencia difusa para definir las variables de entrada (input) y variables de salida (output), sus respectivas reglas difusas. Así mismo, se definieron los instrumentos de recolección de información. Para finalizar, en el quinto capítulo se realiza la simulación del modelo Tipologías Policía para el Desarrollo Humano (TPDH).
